# Generated by Django 4.1.7 on 2023-06-21 11:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alarm_audit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('schedule_audit_id', models.IntegerField()),
                ('alarm_number', models.IntegerField(default=-1)),
                ('sent_time', models.IntegerField(default=-1)),
                ('actual_time', models.IntegerField(default=-1)),
            ],
            options={
                'verbose_name': 'Alarm_Audit',
                'verbose_name_plural': 'Audits_Alarm',
            },
        ),
        migrations.CreateModel(
            name='dispense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('schedule_id', models.IntegerField(default=-1)),
                ('dispense_time', models.DateTimeField(default=datetime.datetime.now)),
                ('alarms_start_time', models.DateTimeField(default=datetime.datetime.now)),
                ('alarms_end_time', models.DateTimeField(default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Dispense',
                'verbose_name_plural': 'Dispense',
            },
        ),
        migrations.CreateModel(
            name='reminder_schedule_audit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dispense_id', models.IntegerField(default=-1)),
                ('dispense_consumed', models.BooleanField(default=False)),
                ('date_of_alarms', models.DateTimeField(default=datetime.datetime.now)),
                ('alarm_count', models.IntegerField(default=-1)),
            ],
            options={
                'verbose_name': 'Reminder_Audit_schedule',
                'verbose_name_plural': 'Reminder_Audits',
            },
        ),
        migrations.CreateModel(
            name='reminder_schedule_groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_in_mins', models.IntegerField(default=-1)),
                ('recurring', models.IntegerField(default=-1)),
                ('No_of_alarms_before_dispense', models.IntegerField(default=-1)),
                ('No_of_alarms_after_dispense', models.IntegerField(default=-1)),
                ('time_range_between_alarms', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Reminder_schedule',
                'verbose_name_plural': 'Reminders',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('dob', models.DateField(blank=True, max_length=8, null=True)),
                ('trial_enrollment_date', models.DateField(blank=True, max_length=8, null=True)),
                ('age', models.IntegerField()),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('contact_no', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact phone number', max_length=128, region=None)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('nominee_name', models.CharField(blank=True, max_length=50, null=True)),
                ('nominee_mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='nominee phone number', max_length=128, region=None)),
                ('postal_code', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('country', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('current_doctor', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('doctors_pic', models.ImageField(blank=True, default='', upload_to='images/')),
                ('diagnosis', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('allergies', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('medication_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('medicine_pic', models.ImageField(blank=True, default='', upload_to='images/')),
                ('dosage_time1', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('dosage_time2', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('device_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'verbose_name': 'User_profile',
                'verbose_name_plural': 'User_profiles',
            },
        ),
        migrations.CreateModel(
            name='provisioning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_id', models.CharField(max_length=25)),
                ('public_ip', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'verbose_name': 'device',
                'verbose_name_plural': 'devices',
            },
        ),
        migrations.CreateModel(
            name='medicine_dispense_information',
            fields=[
                ('dispense_id', models.AutoField(primary_key=True, serialize=False)),
                ('dispense', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'verbose_name': 'medicine_dispense',
                'verbose_name_plural': 'medicines',
            },
        ),
    ]
