# Generated by Django 4.1.7 on 2023-06-20 11:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='allergies',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user_info',
            name='contact_no',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact phone number', max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='user_info',
            name='doctors_pic',
            field=models.ImageField(blank=True, default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='user_info',
            name='dosage_time1',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='user_info',
            name='dosage_time2',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='user_info',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user_info',
            name='medication_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user_info',
            name='medicine_pic',
            field=models.ImageField(blank=True, default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='user_info',
            name='nominee_mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='nominee phone number', max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='user_info',
            name='nominee_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user_info',
            name='patient_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AlterField(
            model_name='dispense',
            name='alarms_end_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='dispense',
            name='alarms_start_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='dispense',
            name='dispense_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='reminder_schedule_audit',
            name='date_of_alarms',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
