# Generated by Django 4.1.7 on 2023-06-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_reviewed_medicine_dispense_information_video_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine_dispense_information',
            name='points',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
    ]
