# Generated by Django 4.1.7 on 2023-06-21 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_medicine_dispense_information_dispense_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine_dispense_information',
            name='user_id',
        ),
    ]
