# Generated by Django 4.1.7 on 2023-06-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_medicine_dispense_information_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_info',
            old_name='doctors_pic',
            new_name='clinician_pic',
        ),
        migrations.RenameField(
            model_name='user_info',
            old_name='current_doctor',
            new_name='current_clinician',
        ),
        migrations.RenameField(
            model_name='user_info',
            old_name='medication_name',
            new_name='medicine_name',
        ),
        migrations.AddField(
            model_name='user_info',
            name='dose_duration',
            field=models.IntegerField(default=-1),
        ),
    ]
