# Generated by Django 4.1.7 on 2023-06-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_doctors_pic_user_info_clinician_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='dose_per_day',
            field=models.IntegerField(default=-1),
        ),
    ]
