# Generated by Django 4.1.7 on 2023-06-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_info_dose_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='dosage_time1',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='dosage_time2',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
