# Generated by Django 4.1.7 on 2023-06-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_info_dosage_time1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='dosage_time1',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='dosage_time2',
            field=models.TimeField(blank=True),
        ),
    ]
