# Generated by Django 4.1.7 on 2023-07-11 13:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_reminder_schedule_groups_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capture_event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_btn', models.DateTimeField(default=datetime.datetime.now)),
                ('notification_btn', models.DateTimeField(default=datetime.datetime.now)),
                ('home_btn', models.DateTimeField(default=datetime.datetime.now)),
                ('dispense_btn', models.DateTimeField(default=datetime.datetime.now)),
                ('reminder_btn', models.DateTimeField(default=datetime.datetime.now)),
                ('travel_btn', models.DateTimeField(default=datetime.datetime.now)),
                ('contact_btn', models.DateTimeField(default=datetime.datetime.now)),
                ('sideeffect_btn', models.DateTimeField(default=datetime.datetime.now)),
                ('setting_btn', models.DateTimeField(default=datetime.datetime.now)),
                ('coaching_btn', models.DateTimeField(default=datetime.datetime.now)),
                ('dose_schedule_btn', models.DateTimeField(default=datetime.datetime.now)),
                ('reminder_group_btn', models.DateTimeField(default=datetime.datetime.now)),
                ('med_review_btn', models.DateTimeField(default=datetime.datetime.now)),
                ('profile_btn', models.DateTimeField(default=datetime.datetime.now)),
                ('edit_profile_btn', models.DateTimeField(default=datetime.datetime.now)),
                ('default_option_btn', models.DateTimeField(default=datetime.datetime.now)),
                ('my_reminder_btn', models.DateTimeField(default=datetime.datetime.now)),
                ('performance_btn', models.DateTimeField(default=datetime.datetime.now)),
                ('learning_btn', models.DateTimeField(default=datetime.datetime.now)),
                ('community_btn', models.DateTimeField(default=datetime.datetime.now)),
                ('events_btn', models.DateTimeField(default=datetime.datetime.now)),
                ('help_btn', models.DateTimeField(default=datetime.datetime.now)),
                ('msg_template_btn', models.DateTimeField(default=datetime.datetime.now)),
                ('msg_family_btn', models.DateTimeField(default=datetime.datetime.now)),
                ('msg_clinical_btn', models.DateTimeField(default=datetime.datetime.now)),
                ('msg_coherence_btn', models.DateTimeField(default=datetime.datetime.now)),
                ('stop_recording_btn', models.DateTimeField(default=datetime.datetime.now)),
                ('load_medication_btn', models.DateTimeField(default=datetime.datetime.now)),
                ('more_menu_btn', models.DateTimeField(default=datetime.datetime.now)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'verbose_name': 'Capture_event',
                'verbose_name_plural': 'Capture_events',
            },
        ),
    ]
