# Generated by Django 4.1.7 on 2023-07-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_capture_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Broacasting_type', models.CharField(blank=True, max_length=25, null=True)),
                ('Header_ID', models.CharField(blank=True, max_length=25, null=True)),
                ('Blood_oxygen', models.CharField(blank=True, max_length=25, null=True)),
                ('Stress_level', models.CharField(blank=True, max_length=25, null=True)),
                ('RRI_HRV', models.CharField(blank=True, max_length=25, null=True)),
                ('Activity_Intensity', models.CharField(blank=True, max_length=25, null=True)),
                ('Blood_pressure_SBP', models.CharField(blank=True, max_length=25, null=True)),
                ('Blood_pressure_DBP', models.CharField(blank=True, max_length=25, null=True)),
                ('calorie', models.CharField(blank=True, max_length=25, null=True)),
                ('surface_temperature', models.CharField(blank=True, max_length=25, null=True)),
                ('body_temperature', models.CharField(blank=True, max_length=25, null=True)),
                ('heart_rate', models.CharField(blank=True, max_length=25, null=True)),
                ('sos', models.CharField(blank=True, max_length=25, null=True)),
                ('battery', models.CharField(blank=True, max_length=25, null=True)),
                ('beacon_battery', models.CharField(blank=True, max_length=25, null=True)),
                ('Device_name', models.CharField(blank=True, max_length=25, null=True)),
                ('Total', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
    ]
