# Generated by Django 4.1.7 on 2023-06-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trial_name', models.CharField(max_length=25)),
                ('Pharma_company', models.CharField(max_length=50)),
                ('CRO', models.CharField(max_length=25)),
                ('Trial_Id', models.IntegerField(default=-1)),
                ('CRO_Trial_Id', models.IntegerField(default=-1)),
                ('medication1_id', models.IntegerField(default=-1)),
                ('medication2_id', models.IntegerField(default=-1)),
            ],
            options={
                'verbose_name': 'trial',
                'verbose_name_plural': 'trials',
            },
        ),
    ]
